import type { Metadata } from "next";
import React from "react";
import Header from "@/components/layout/headers/header";
import Footer from "@/components/layout/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="antialiased">
      <Header />
      <main>{children}</main>
      <Footer />
    </div>
  );
}
